version: '3'
services:
  influxdb:
    restart: always
    # for raspberry pi 64 bit
    image: dopplertx/influxdb-2.0-arm64
    # image: quay.io/influxdb/influxdb:2.0.0-beta
    volumes:
      - influxdb:/root/.influxdbv2
    ports:
      - 9999:9999

  grafana:
    depends_on:
      - influxdb
    restart: always
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana-plugins:/var/lib/grafana/plugins
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000

  udp-client:
    build:
      context: ./udp-client
      dockerfile: Dockerfile
    image: node-weatherflow-udp-client:latest
    restart: always
    ports:
      - 50222:50222/udp
    depends_on:
      - influxdb
      - grafana

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - influxdb
      - grafana
      - udp-client

volumes:
  influxdb:
  grafana:
