{
 "title": "Wind and Temperature",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wind Direction and Speed",
   "type": "doppler-windchart-panel",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rapid_wind\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dir\" or r[\"_field\"] == \"mps\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"obs_st\")\n  |> filter(fn: (r) => r[\"_field\"] == \"airTemperature\")\n  |> map(fn: (r) => ({ r with _value: ( r._value * 9.0 / 5.0) + 32.0 }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature and Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Temperature °F" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "T = from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"obs_st\")\n  |> filter(fn: (r) => r[\"_field\"] == \"airTemperature\")\n  |> map(fn: (r) => ({ _time: r._time, _value: (r._value * 9.0 / 5.0) + 32.0, _field: \"Temperature °F\"}))\n  |> yield(name: \"T\")\n\nH = from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"obs_st\")\n  |> filter(fn: (r) => r[\"_field\"] == \"relativeHumidity\")\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value, _field: \"Relative Humidity %\"}))\n  |> yield(name: \"relative humidity\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"obs_st\")\n  |> filter(fn: (r) => r[\"_field\"] == \"relativeHumidity\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind ( Lull / Avg / Gust )",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "MPH" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"obs_st\")\n  |> filter(fn: (r) => r[\"_field\"] == \"windLull\")\n  |> map(fn: (r) => ({ _time: r._time, _field: \"Lull\", _value: r._value * 2.237 }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"obs_st\")\n  |> filter(fn: (r) => r[\"_field\"] == \"windAvg\")\n  |> map(fn: (r) => ({ _time: r._time, _field: \"Avg\", _value: r._value * 2.237 }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"obs_st\")\n  |> filter(fn: (r) => r[\"_field\"] == \"windGust\")\n  |> map(fn: (r) => ({ _time: r._time, _field: \"Gust\", _value: r._value * 2.237 }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"weatherflow\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rapid_wind\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mps\")\n  |> map(fn: (r) => ({ _time: r._time, _field: \"Instantaneous\", _value: r._value * 2.237 }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}